SET CHARSET UTF8;
CREATE DATABASE IF NOT EXISTS todo DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS todo
(
  id           INT AUTO_INCREMENT,
  typename     VARCHAR(40),
  todo         VARCHAR(40),
  PRIMARY KEY (id)
);